spring:
  application:
    name: currency-conversion
  cloud:
    config:
      enabled: false

server:
  port: 8100

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka